### PR TITLE
 Merge branch 'cam_development (cam6_3_020 and cam6_3_024)' into cam_mpas_dev 

### PR DESCRIPTION
**Pull request by MiCurry**
This merge brings cam_mpas_dev up to date with the CAM tag cam6_3_020 and cam6_3_024.

### CODE REVIEW

**Comment by MiCurry** [comment]
@jtruesdal I will merge this into cam_mpas_dev tomorrow morning. I just ran these changes through the cases I have listed in the Running CAM-MPAS Document. Let me know if you have any tests you'd like to preform before I merge it in.

**Comment by jtruesdal** [comment]
@MiCurry I'll run a few regression tests this evening and let you know if there are any issues.

**Comment by jtruesdal** [comment]
regression tests look good.  If you need help with the conflicting files I corrected them for my testing.
/glade/p/cgd/amp/jet/collections/cam_mpas_dev.062821

**Comment by MiCurry** [comment]
@jtruesdal thanks for running the regression tests! I think I'll be good on the conflicts, but I'll double check with yours that you have linked. Thanks again.

**Pull request merged**
