### PR TITLE
Update MPAS Dycore to work with new physics, dynamics interface

### PR DESCRIPTION
**Pull request by MiCurry**
This commit updates the MPAS dycore to use the new physics, dynamics infrastructure introduced in e3630ff. It adds a new function, get_dyn_grid_info, in dyn_grid, which fills out an array of `physics_column_t` structures to describe its dynamics columns. This array of `physics_column_t` is requested by the changes in e3630ff and is used to translate between physics and dynamics columns.

It then updates `d_p_coupling` and `p_d_coupling` to use `get_chunk_info_p` and `get_dyn_col_p` to get dynamics and physics column indices. e3630ff also removes chunking, so this PR removes chunking information from both coupling functions.

### CODE REVIEW

**Comment by MiCurry** [comment]
@mgduda @jtruesdal here are my changes for implementing the weak scaling fixes into the MPAS dycore. @jtruesdal I think we'll need to update your `cam_development` branch with the `cam_development` branch of ESCOMP/CAM's, which will remove the commits added by goldy.

Please review and test at your convenience!

**Comment by jtruesdal** [comment]
I completed bringing my cam fork up to the head of cam_development and merged these weak scaling mods in a branch called mpas_fixes_weak_scaling.  I have done some testing but am running into some small issues which I am looking into.  Once I've debugged and tested this branch I'll merge it on the main mpas_fixes branch for the PR.

**Comment by MiCurry** [comment]
@jtruesdal Let me know what problems you've had and I'll be happy to clean them up.

Also, just a suggestion, would it be easier if we change the target of this branch to something other then cam_development?

As well, I noticed that you updated your branch using merges. I have found that it's easier to update the branches on a personal fork to a main fork using `git reset --hard [origin]/[branch]`, that way there aren't unnecessary merge commits, like commit 17430cd. The `--hard` option will discard any changes to that have been made to that branch, as `reset` will directly copy and overwrite `origin/branch` onto the current branch. If changes need to be preserved then `git rebase branch`, which places the commits of a branch on top of another one.

So for instance, if you `git reset --hard [cam-remote]/cam_development` you'll get an exact copy of the current ESCOMP cam_development branch (assuming you have used `git fetch` to fetch updated ESCOMP changes).

And that makes me think perhaps targeting another branch, one that's up to date with `ESCOMP/cam_development`, say `mpas_dycore_updates`. I think doing so would make this PR easier to read, as it would only contain the commits I've made on my `cam-mpas/weak_scaling_fix` and it doesn't change the commit numbers of Steve's weak scaling changes. If you notice, the commit hashes for Steve's changes on your `cam_development` do not match the hashes for the same commits on `ESCOMP/cam_development` (which is why they are showing up in this commit).

Let me know what you think of that or if you have another means of managing forks and branches. I'd also be happy to have a ~15 - 25 min meeting to go over this!

**Comment by jtruesdal** [comment]
Thanks Miles.  I'm certainly less experienced at using Github and am
looking forward to learning a better way to handle this.  Let me go through
the details of your email and make sure I understand what you are
recommending and then let's talk to move forward with something. I'll get
back to you about that soon.

As for the error.  I was doing some testing last week to verify that a
two-month run matched a one month and restart.  I think the restart run was
failing as it was writing the final dataset.
If you could duplicate that test with your code setup that would help.  If
it works then there is a problem with my merge up to cam_development.  If
that's the case then maybe we could move right on to creating a clean
branch with all the appropriate changes as I will need that for the PR.

My case directory is:
/glade/p/cgd/amp/jet/cases/QPC6.mpasa480_mpasa480.intel.144x1pes.chey.mpas_fixes_plus_weak_scaling.001
The run directory with logs from 1 month as well as the failure log when
trying to finish up the IO at the end of the second month is:
/glade/scratch/jet/QPC6.mpasa480_mpasa480.intel.144x1pes.chey.mpas_fixes_plus_weak_scaling.001/run

jt

**Comment by MiCurry** [comment]
@jtruesdal let me know if you would like a demonstration, I'd be happy to provide one. As well, if you do mess around with `git reset`, its always a good idea to make a backup of your fork (i.e. `git clone` and then `git fetch`) in case something gets wonky.

Sounds good, I'll go ahead and take a look at your test and see if I can duplicate it.

**Comment by MiCurry** [comment]
@jtruesdal I was able to run a two month QPC6 run and then ran a 1 month restart off of the output of the the two month run, which you can find at `/glade/scratch/mcurry/jet-weak-scale-qpc6-144-test`.

I was able to run both successfully, but I noticed that my second run differed from your first. Notably that my second run had:

```
  ------------------------------------------
  *********** CAM LOG OUTPUT ***************
  ------------------------------------------
          Initial run
```

at the top of its atm.log, while yours had:
```
  ------------------------------------------
  *********** CAM LOG OUTPUT ***************
  ------------------------------------------
   Restart of an earlier run
```

Do you know why there is this difference? If you take a look at my run directory, let me know if there's something I've missed.

**Comment by MiCurry** [comment]
This PR is currently in the mpas_fixes branch and is being reviewed to be put into ESCOMP/cam_development. So I'm going to close this PR.

**Pull request closed without merging**
